# Generated by Django 2.2 on 2020-02-10 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20200210_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='servings',
            field=models.SmallIntegerField(default=1),
        ),
    ]
