# Generated by Django 2.2.10 on 2020-02-13 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_recipeingredients_api_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredients',
            name='api_unit',
            field=models.CharField(max_length=255),
        ),
    ]
