# Generated by Django 2.2 on 2020-02-10 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0003_product_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='grams',
            field=models.DecimalField(decimal_places=12, default=0, max_digits=24),
        ),
    ]
