# Generated by Django 2.2 on 2020-02-10 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0004_unit_grams'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='mililiters',
            field=models.DecimalField(decimal_places=12, default=0, max_digits=24),
        ),
    ]
