# Generated by Django 2.2 on 2020-02-10 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0007_product_pieces'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='grams_per_piece',
        ),
        migrations.RemoveField(
            model_name='product',
            name='mililiters_per_piece',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pieces',
        ),
        migrations.AddField(
            model_name='product',
            name='default_quantity',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
        ),
    ]
