# Generated by Django 2.2 on 2020-02-12 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0010_auto_20200211_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='default_unit',
        ),
        migrations.RemoveField(
            model_name='product',
            name='grams_per_piece',
        ),
        migrations.RemoveField(
            model_name='product',
            name='mililiters_per_piece',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pieces',
        ),
        migrations.AddField(
            model_name='product',
            name='api_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='Unit',
        ),
    ]
